### ISSUE TITLE
Find a way to embed the language server coming from grammarly

### ISSUE THREAD

**Issue by gianarb** [gianarb/coc-grammarly#1]
https://github.com/gianarb/coc-grammarly/blob/master/src/index.ts#L8

This does not have any sense obviously, we have to create the right structure around what Grammarly already provides, but it should be required to pass the js file here directly.

Vim COC exposes utilities that I have to learn

**Comment by iamcco** [comment]
You can add grammarly as dependency or bundle grammarly in your repo.

You can have a look at https://github.com/iamcco/coc-diagnostic/blob/master/src/index.ts#L42

**Comment by gianarb** [comment]
Hello @iamcco ! Yeah, I thought about it, do you think I should add Grammarly as git submodule here? (other than giving an option to point to you your own version of it?)

Thanks!

**Comment by iamcco** [comment]
I don't know if npm support submodule. It's good idea to have an option to point custom version.

**Comment by gianarb** [comment]
This is what I did, for now, https://github.com/gianarb/coc-grammarly/commit/9eeadb0ecfb87bcd1d5acaba05c117732d221e96, not the best wat, I am also not sure about how to pass configurations and things like that yet but it works

I hope at some point Grammarly won't depend on vscode engine and it will become a bit easier to import via npm.

I will keep going and looking around to see if I can do something better than this
